[package]
name = "redis_sample"
version = "0.1.0"
authors = ["marceloserpa <jdev.marcelo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.12.0"